### ISSUE TITLE
Cookie expiration

### ISSUE THREAD

**Issue by pserna95** [andreasonny83/angular2-cookie-law#13]
Hi @andreasonny83, I'm using your library in my personal project just HTML like that:
```
  <cookie-law name="cookieName" learnMore="/privacity">
    Some text inside the cookie banner.
    <a [routerLink]="['/privacity']">Learn more</a>
  </cookie-law>
```
So, the library is fantastic but I cannot set the expiration time of the cookie so when I close the browser, the cookie expires. Is there any posibility of setting cookie's duration for more than the session of the browser? Maybe setting it for a year or something.

I'm really thankful and waiting for your response!  

Pablo

**Comment by andreasonny83** [comment]
Hey @pserna95.
Thanks for your feedback, first of all.
And yes, I noticed the same issue and I was about to implement that feature. So, thanks to your help I'm just going to work on that. I will report this issue as closed as soon as I release the new version containing that feature.

Thanks again.

**Comment by andreasonny83** [comment]
@pserna95 , It should now being available on version 1.3.0. Have a look at the documentation and let me know if that works.
https://github.com/andreasonny83/angular2-cookie-law#expire

**Comment by pserna95** [comment]
@andreasonny83 Tested and working perfectly! Thanks! 🥇

**Comment by dothem1337** [comment]
Why does this not work on my project? I set the expiration, but the banner always shows up :S
