### ISSUE TITLE
Button dismiss

### ISSUE THREAD

**Issue by redfish31** [andreasonny83/angular2-cookie-law#14]
Hi,

I have a problem with the dismiss button : 

`ERROR TypeError: Cannot read property 'dismiss' of undefined`

I have this code in my component HTML : 
`<cookie-law position="bottom">`
  `<div class="container">`
    `<div class="row">`
      `<div class="col l10">`
        `<div class="cookie-title">Nous utilisons des cookies</div>
        `<div class="cookie-text">En poursuivant la navigation, vous acceptez l'installation et l'utilisation des cookies sur votre ordinateur.</div>`
        `<div class="cookie-text-orange"><a href="/page-cgu#cookies">> En savoir plus</a></div>`
     `</div>`
     ` <div class="col l2"><button class="white-text amber darken-1 waves-effect waves-light btn depo cookie-btn" (click)="dismiss()">J'accepte</button></div>`
    `</div>`
  `</div>`
`</cookie-law>`

And in my component TS : 
`@ViewChild('cookieLaw') 
  cookieLawEl: any;
...
public dismiss(): void {
    this.cookieLawEl.dismiss();
  }
`

Can you help me please ?

Thx

**Comment by andreasonny83** [comment]
Hi @redfish31 ,
what you're missing in your code is the reference in the DOM to the ViewChild  `cookieLaw`.
What you have to do in your HTML template, is to add an `#cookieLaw` like this:

```
<cookie-law #cookieLaw position="bottom">
  <div class="container">
    <div class="row">
      <div class="col l10">
        <div class="cookie-title">Nous utilisons des cookies</div>
      </div>
    </div>
  </div>
</cookie-law>
```

**Comment by redfish31** [comment]
Hi @andreasonny83,

Thank you, it's ok !
