### ISSUE TITLE
Add rel="noopener" to target="_blank" to prevent window.opener vulnerability

### ISSUE THREAD

**Issue by jacobedawson** [andreasonny83/angular2-cookie-law#15]
Hi - thanks for making this module :) 

There is a known vulnerability with the target="_blank" attribute on anchor links, and this is now being flagged by Google's Lighthouse, for example. 

The solution would be to add an option to include the rel="noopener" & rel="noreferrer" (for Firefox) attributes to the 'read more' anchor link. You could also just add it by default. 

More information about this vulnerability can be read here: 
https://developers.google.com/web/tools/lighthouse/audits/noopener
https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/
https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

**Comment by andreasonny83** [comment]
that's really interesting @jacobedawson . Thanks for highlighting that one.
I'm gonna have a look at those documentations and try to release a new version of the library soon.

**Comment by andreasonny83** [comment]
@jacobedawson please let me know if the new version is good enough for you

**Comment by jacobedawson** [comment]
Cool man, looks good!
