### ISSUE TITLE
Changing the svg icon

### ISSUE THREAD

**Issue by dottodot** [andreasonny83/angular2-cookie-law#16]
Is it possible to add your own svg icon for dismissing the banner?

**Comment by andreasonny83** [comment]
unfortunately that's not possible at the moment @dottodot

**Comment by pablochud** [comment]
+1

**Comment by RobertThwaite** [comment]
Made pull request which adds ability to use font awsome Icons as a close button.

**Comment by dottodot** [comment]
Thanks for adding the customisable icon option. Wondering if it's worth updating the docs as this isn't really limited to only using fontawesome, you can add any class you want as long as you create the css to display it.

**Comment by andreasonny83** [comment]
Can you do that an send a PR?

**Comment by andreasonny83** [comment]
closed by #18
