### ISSUE TITLE
bug?: regular expression

### ISSUE THREAD

**Issue by wizardfan** [andreasonny83/angular2-cookie-law#20]
The line 35 in src/cookie-law.service.ts reads as
c = ca[i].replace(/^\s\+/g, ''); 

Is it to remove the starting whitespace? If so, then the RE should be ^\s+?

**Comment by andreasonny83** [comment]
You're right, actually it should be
```
c = ca[i].replace(/\s+/g, '');
```
to make sure to remove any white space in the string.
I'm going to release a patched version soon.

Thanks @wizardfan
