### ISSUE TITLE
Custom Template

### ISSUE THREAD

**Issue by VanDxtr** [andreasonny83/angular2-cookie-law#25]
> It is possible to overwrite our default cookie policy law text with a custom template. Just put your favorite html content between the component like in the following example:

`<cookie-law position="top">
  This website contains cookie.
  <a href="#/cookie-policy">Read more</a>
</cookie-law>`

For me this one don't work!!! 
I add to axactly the same code and when i change the text it return always "By continuing to browse the site, you're agreeing to our use of cookies.". 
How can i resolve ?

**Comment by andreasonny83** [comment]
@VanDxtr , the live demo project is using the custom template feature and it's working.
Please have a look at the live project available [here](https://stackblitz.com/edit/angular2-cookie-law?file=src%2Fapp%2Fapp.component.html).
I'm going to close this ticket as I cannot reproduce the bug.
If the problem persists, please reopen this issue and include your `package.json` file.

**Comment by VanDxtr** [comment]
Are you serious? it does not even work in the online demo version. in the picture does not seem to me that the text changes with what I put....
![foto](https://user-images.githubusercontent.com/26846790/40872325-a7df7840-664c-11e8-92c1-195953486464.png)

**Comment by andreasonny83** [comment]
@VanDxtr, you're perfectly right, I'm sorry. I'll have a look at this ASAP.
Thanks for the feedback.

**Comment by VanDxtr** [comment]
so did you fix this bug?

**Comment by VanDxtr** [comment]
@andreasonny83

**Comment by andreasonny83** [comment]
no sorry, is not fixed yet. 
I reopened the issue. Anyway, pull requests are always more than welcome, considering I don't have enough time to dedicate to this project.
