### ISSUE TITLE
changing text

### ISSUE THREAD

**Issue by SylTi** [andreasonny83/angular2-cookie-law#3]
Hey there,
Thanks a lot for your great work!
Do you think you could make the text configurable for the next release? 
It will help a lot for multilingual sites.
If you don't have time right now I will make a pull request in few days.

Thanks !

**Comment by andreasonny83** [comment]
I will try to release a release with that implementation in record time.
Thanks a lot for your feedback

**Comment by andreasonny83** [comment]
I hope the new release will fix your issue. Let me know if not

**Comment by SylTi** [comment]
Perfect thanks!

**Comment by andreasonny83** [comment]
Let me know if you need more features or changes or just raise a pull request, that would be awesome. Thanks again
