### ISSUE TITLE
make a new release on npmjs

### ISSUE THREAD

**Issue by robindijkhof** [andreasonny83/angular2-cookie-law#34]
I saw some ssr fixes were merged. Though there is a 6.1.0 tag on github, it is not on npm.

**Comment by Bidthedog** [comment]
I could do with this - think its been a few months since the initial issue was fixed - npm has v 6.0.4, which doesn't have the SSR fixes in it. Here's a bit of relevant transpiled server.js code:

    function (cookieName) {
        if (cookieName === void 0) { cookieName = 'cookieLawSeen'; }
        var /** @type {?} */ cookies = document.cookie.split(';');
        return this.cookieExisits(cookieName, cookies);
    };

**Comment by andreasonny83** [comment]
Sorry about the delay.
A newer version 6.2.0 is now available on npm.
https://github.com/andreasonny83/angular2-cookie-law/releases/tag/v6.2.0
