### ISSUE TITLE
v6.1.0 is not available on npm

### ISSUE THREAD

**Issue by neilime** [andreasonny83/angular2-cookie-law#36]
Hi,

Can you push the last release "v6.1.0" on NPM ?

Thank you

**Comment by andreasonny83** [comment]
I'm doing that now. Thanks for pointing that out @neilime

**Comment by andreasonny83** [comment]
Sorry about the delay.
A newer version 6.2.0 is now available on npm.
https://github.com/andreasonny83/angular2-cookie-law/releases/tag/v6.2.0
