### ISSUE TITLE
Live demo version does not work

### ISSUE THREAD

**Issue by damianszczepanik** [andreasonny83/angular2-cookie-law#41]
When opening https://stackblitz.com/edit/angular2-cookie-law?file=src%2Fapp%2Fapp.component.html on Firefox or Chrome it tries to load the page forever and no content is presented.

**Comment by andreasonny83** [comment]
@damianszczepanik is this still happening? I can correctly open the link with no problems

**Comment by damianszczepanik** [comment]
Link is working correctly but content is not uploaded on merge to master

**Comment by andreasonny83** [comment]
I'm not sure what you mean by that. I just created a new demo for Angular 7 using the latest 7.0.1 version of this package and everything looks fine on my end. https://citymapper.com/trip/Tkb8pp8vgh5

**Comment by damianszczepanik** [comment]
Looks fine, maybe temporary problem with hosted app
